import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../models/models.dart';
import '../services/api_client.dart';

/// "Ask Brod" — the read-only operations assistant (§ intelligence). A chat over the platform's own
/// failure data: each question goes to {@code POST /api/assistant/ask}, which grounds a self-hosted
/// model in the current incidents/failures (PII-masked) and returns a cited answer. It answers and
/// summarises only — it never takes actions, so verify before acting.
class AssistantScreen extends StatefulWidget {
  const AssistantScreen({super.key});

  @override
  State<AssistantScreen> createState() => _AssistantScreenState();
}

/// One question/answer exchange in the conversation.
class _Turn {
  final String question;
  AssistantAnswer? answer;
  String? error;
  bool loading;
  _Turn(this.question, {this.answer, this.error, this.loading = true});
}

class _AssistantScreenState extends State<AssistantScreen> {
  final TextEditingController _input = TextEditingController();
  final ScrollController _scroll = ScrollController();
  final List<_Turn> _turns = [];
  bool _sending = false;

  static const _suggestions = [
    'Why are payments failing?',
    'Summarize the active incidents',
    'Which topic has the most failures?',
    'What should I look at first?',
  ];

  @override
  void dispose() {
    _input.dispose();
    _scroll.dispose();
    super.dispose();
  }

  Future<void> _send([String? preset]) async {
    final question = (preset ?? _input.text).trim();
    if (question.isEmpty || _sending) return;
    final turn = _Turn(question);
    setState(() {
      _turns.add(turn);
      _input.clear();
      _sending = true;
    });
    _scrollToEnd();
    try {
      final answer = await context.read<ApiClient>().askAssistant(question);
      if (!mounted) return;
      setState(() {
        turn.answer = answer;
        turn.loading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        turn.error = '$e';
        turn.loading = false;
      });
    } finally {
      if (mounted) setState(() => _sending = false);
      _scrollToEnd();
    }
  }

  void _scrollToEnd() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scroll.hasClients) {
        _scroll.animateTo(_scroll.position.maxScrollExtent,
            duration: const Duration(milliseconds: 250), curve: Curves.easeOut);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 18, 20, 6),
          child: Row(
            children: [
              const Icon(Icons.auto_awesome, color: Colors.indigo),
              const SizedBox(width: 8),
              Text('Ask Brod', style: Theme.of(context).textTheme.titleLarge),
              const SizedBox(width: 16),
              const Expanded(
                child: Text(
                  'Answers are generated by your self-hosted model from PII-masked failure data. '
                  'Read-only — verify before acting.',
                  style: TextStyle(fontSize: 12, color: Colors.black54),
                ),
              ),
            ],
          ),
        ),
        const Divider(height: 1),
        Expanded(
          child: _turns.isEmpty
              ? _emptyState()
              : ListView.builder(
                  controller: _scroll,
                  padding: const EdgeInsets.all(20),
                  itemCount: _turns.length,
                  itemBuilder: (context, i) => _turnView(_turns[i]),
                ),
        ),
        _inputBar(),
      ],
    );
  }

  Widget _emptyState() {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(Icons.auto_awesome, size: 48, color: Colors.indigo),
          const SizedBox(height: 12),
          const Text('Ask a question about your failures and incidents',
              style: TextStyle(fontSize: 16)),
          const SizedBox(height: 16),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            alignment: WrapAlignment.center,
            children: [
              for (final s in _suggestions)
                ActionChip(label: Text(s), onPressed: () => _send(s)),
            ],
          ),
        ],
      ),
    );
  }

  Widget _turnView(_Turn turn) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Align(
          alignment: Alignment.centerRight,
          child: Container(
            margin: const EdgeInsets.only(bottom: 8, left: 60),
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              color: Colors.indigo.withOpacity(0.10),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Text(turn.question),
          ),
        ),
        Container(
          margin: const EdgeInsets.only(bottom: 20, right: 60),
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: Colors.grey.withOpacity(0.08),
            borderRadius: BorderRadius.circular(10),
            border: Border.all(color: Colors.black12),
          ),
          child: turn.loading
              ? const Row(mainAxisSize: MainAxisSize.min, children: [
                  SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2)),
                  SizedBox(width: 10),
                  Text('Thinking…', style: TextStyle(color: Colors.black54)),
                ])
              : turn.error != null
                  ? Text('Error: ${turn.error}', style: const TextStyle(color: Colors.red))
                  : _answerView(turn.answer!),
        ),
      ],
    );
  }

  Widget _answerView(AssistantAnswer a) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(a.grounded ? Icons.auto_awesome : Icons.info_outline,
                size: 16, color: a.grounded ? Colors.indigo : Colors.orange),
            const SizedBox(width: 6),
            Text(a.grounded ? 'Brod' : 'Assistant',
                style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13)),
            if (a.grounded) ...[
              const Spacer(),
              Text('grounded in ${a.contextSize} record(s)',
                  style: const TextStyle(fontSize: 11, color: Colors.black45)),
            ],
          ],
        ),
        const SizedBox(height: 6),
        SelectableText(a.answer),
        if (a.citations.isNotEmpty) ...[
          const SizedBox(height: 10),
          const Text('Sources', style: TextStyle(fontSize: 11, color: Colors.black54)),
          const SizedBox(height: 4),
          Wrap(
            spacing: 6,
            runSpacing: 6,
            children: [
              for (final c in a.citations.take(20))
                Chip(
                  label: Text(c, style: const TextStyle(fontSize: 11)),
                  visualDensity: VisualDensity.compact,
                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
            ],
          ),
        ],
      ],
    );
  }

  Widget _inputBar() {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 10, 20, 16),
      decoration: const BoxDecoration(
        border: Border(top: BorderSide(color: Colors.black12)),
      ),
      child: Row(
        children: [
          Expanded(
            child: TextField(
              controller: _input,
              onSubmitted: (_) => _send(),
              decoration: const InputDecoration(
                hintText: 'Ask about failures, incidents, root causes…',
                border: OutlineInputBorder(),
                isDense: true,
                contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 12),
              ),
            ),
          ),
          const SizedBox(width: 8),
          FilledButton.icon(
            onPressed: _sending ? null : () => _send(),
            icon: const Icon(Icons.send, size: 18),
            label: const Text('Ask'),
          ),
        ],
      ),
    );
  }
}
